language: python

cache: pip

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  - python setup.py install

after_success:
    - codecov
    - coveralls
