language: python

cache: pip

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
  - python: 3.6
    env: mode=codestyle
  - python: "3.7"
    dist: xenial
    sudo: false

install:
  - if [[ ! -v mode ]]; then pip install -r requirements.txt; fi
  - if [[ ! -v mode ]]; then pip install coveralls codecov; fi
  - if [[ $mode == codestyle ]]; then pip install pycodestyle; fi

script:
  - if [[ ! -v mode ]]; then python setup.py install; fi
  - if [[ $mode == codestyle ]]; then pycodestyle rt.py; fi

after_success:
  - if [[ ! -v mode ]]; then codecov; fi
